// 색상 테마 정의
export const colorThemes = [
    {
        bgPrimary: "bg-emerald-800/10",
        bgGradient: "bg-gradient-to-r from-emerald-800/10 via-green-800/15 to-lime-800/10",
        svgFill: "cyan",
        textPrimary: "text-emerald-200",
        textHover: "text-emerald-50",
        iconColor: "text-emerald-300/60",
        iconHover: "text-emerald-200",
        decorPrimary: "bg-emerald-400/20",
        decorSecondary: "bg-green-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-emerald-800/20 via-green-800/25 to-lime-800/20",
        viewerDecorPrimary: "bg-emerald-400/10",
        viewerDecorSecondary: "bg-green-400/10",
        viewerBadgeBg: "bg-emerald-900/30",
        viewerBorder: "border-emerald-700/30",
        viewerDateText: "text-emerald-200/80",
        viewerCardBg: "from-emerald-900/5",
        viewerCardTo: "to-green-900/5",
        viewerTopBorder: "from-emerald-500 via-green-500 to-lime-500",
        viewerProseA: "prose-a:text-emerald-400",
        viewerProseAHover: "hover:prose-a:text-emerald-300",
        viewerProseCode: "prose-code:text-green-300",
        viewerProseBlockquote: "prose-blockquote:border-l-emerald-500",
        viewerProseBlockquoteText: "prose-blockquote:text-emerald-200/90"
    },
    {
        bgPrimary: "bg-blue-800/10",
        bgGradient: "bg-gradient-to-r from-blue-800/10 via-indigo-800/15 to-purple-800/10",
        svgFill: "blue",
        textPrimary: "text-blue-200",
        textHover: "text-blue-50",
        iconColor: "text-blue-300/60",
        iconHover: "text-blue-200",
        decorPrimary: "bg-blue-400/20",
        decorSecondary: "bg-indigo-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-blue-800/20 via-indigo-800/25 to-purple-800/20",
        viewerDecorPrimary: "bg-blue-400/10",
        viewerDecorSecondary: "bg-indigo-400/10",
        viewerBadgeBg: "bg-blue-900/30",
        viewerBorder: "border-blue-700/30",
        viewerDateText: "text-blue-200/80",
        viewerCardBg: "from-blue-900/5",
        viewerCardTo: "to-indigo-900/5",
        viewerTopBorder: "from-blue-500 via-indigo-500 to-purple-500",
        viewerProseA: "prose-a:text-blue-400",
        viewerProseAHover: "hover:prose-a:text-blue-300",
        viewerProseCode: "prose-code:text-indigo-300",
        viewerProseBlockquote: "prose-blockquote:border-l-blue-500",
        viewerProseBlockquoteText: "prose-blockquote:text-blue-200/90"
    },
    {
        bgPrimary: "bg-purple-800/10",
        bgGradient: "bg-gradient-to-r from-purple-800/10 via-pink-800/15 to-rose-800/10",
        svgFill: "purple",
        textPrimary: "text-purple-200",
        textHover: "text-purple-50",
        iconColor: "text-purple-300/60",
        iconHover: "text-purple-200",
        decorPrimary: "bg-purple-400/20",
        decorSecondary: "bg-pink-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-purple-800/20 via-pink-800/25 to-rose-800/20",
        viewerDecorPrimary: "bg-purple-400/10",
        viewerDecorSecondary: "bg-pink-400/10",
        viewerBadgeBg: "bg-purple-900/30",
        viewerBorder: "border-purple-700/30",
        viewerDateText: "text-purple-200/80",
        viewerCardBg: "from-purple-900/5",
        viewerCardTo: "to-pink-900/5",
        viewerTopBorder: "from-purple-500 via-pink-500 to-rose-500",
        viewerProseA: "prose-a:text-purple-400",
        viewerProseAHover: "hover:prose-a:text-purple-300",
        viewerProseCode: "prose-code:text-pink-300",
        viewerProseBlockquote: "prose-blockquote:border-l-purple-500",
        viewerProseBlockquoteText: "prose-blockquote:text-purple-200/90"
    },
    {
        bgPrimary: "bg-orange-800/10",
        bgGradient: "bg-gradient-to-r from-orange-800/10 via-red-800/15 to-pink-800/10",
        svgFill: "orange",
        textPrimary: "text-orange-200",
        textHover: "text-orange-50",
        iconColor: "text-orange-300/60",
        iconHover: "text-orange-200",
        decorPrimary: "bg-orange-400/20",
        decorSecondary: "bg-red-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-orange-800/20 via-red-800/25 to-pink-800/20",
        viewerDecorPrimary: "bg-orange-400/10",
        viewerDecorSecondary: "bg-red-400/10",
        viewerBadgeBg: "bg-orange-900/30",
        viewerBorder: "border-orange-700/30",
        viewerDateText: "text-orange-200/80",
        viewerCardBg: "from-orange-900/5",
        viewerCardTo: "to-red-900/5",
        viewerTopBorder: "from-orange-500 via-red-500 to-pink-500",
        viewerProseA: "prose-a:text-orange-400",
        viewerProseAHover: "hover:prose-a:text-orange-300",
        viewerProseCode: "prose-code:text-red-300",
        viewerProseBlockquote: "prose-blockquote:border-l-orange-500",
        viewerProseBlockquoteText: "prose-blockquote:text-orange-200/90"
    },
    {
        bgPrimary: "bg-teal-800/10",
        bgGradient: "bg-gradient-to-r from-teal-800/10 via-cyan-800/15 to-blue-800/10",
        svgFill: "teal",
        textPrimary: "text-teal-200",
        textHover: "text-teal-50",
        iconColor: "text-teal-300/60",
        iconHover: "text-teal-200",
        decorPrimary: "bg-teal-400/20",
        decorSecondary: "bg-cyan-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-teal-800/20 via-cyan-800/25 to-blue-800/20",
        viewerDecorPrimary: "bg-teal-400/10",
        viewerDecorSecondary: "bg-cyan-400/10",
        viewerBadgeBg: "bg-teal-900/30",
        viewerBorder: "border-teal-700/30",
        viewerDateText: "text-teal-200/80",
        viewerCardBg: "from-teal-900/5",
        viewerCardTo: "to-cyan-900/5",
        viewerTopBorder: "from-teal-500 via-cyan-500 to-blue-500",
        viewerProseA: "prose-a:text-teal-400",
        viewerProseAHover: "hover:prose-a:text-teal-300",
        viewerProseCode: "prose-code:text-cyan-300",
        viewerProseBlockquote: "prose-blockquote:border-l-teal-500",
        viewerProseBlockquoteText: "prose-blockquote:text-teal-200/90"
    },
    {
        bgPrimary: "bg-rose-800/10",
        bgGradient: "bg-gradient-to-r from-rose-800/10 via-pink-800/15 to-purple-800/10",
        svgFill: "rose",
        textPrimary: "text-rose-200",
        textHover: "text-rose-50",
        iconColor: "text-rose-300/60",
        iconHover: "text-rose-200",
        decorPrimary: "bg-rose-400/20",
        decorSecondary: "bg-pink-400/20",
        // WeeklyNewsViewer용 추가 속성
        viewerBgGradient: "bg-gradient-to-r from-rose-800/20 via-pink-800/25 to-purple-800/20",
        viewerDecorPrimary: "bg-rose-400/10",
        viewerDecorSecondary: "bg-pink-400/10",
        viewerBadgeBg: "bg-rose-900/30",
        viewerBorder: "border-rose-700/30",
        viewerDateText: "text-rose-200/80",
        viewerCardBg: "from-rose-900/5",
        viewerCardTo: "to-pink-900/5",
        viewerTopBorder: "from-rose-500 via-pink-500 to-purple-500",
        viewerProseA: "prose-a:text-rose-400",
        viewerProseAHover: "hover:prose-a:text-rose-300",
        viewerProseCode: "prose-code:text-pink-300",
        viewerProseBlockquote: "prose-blockquote:border-l-rose-500",
        viewerProseBlockquoteText: "prose-blockquote:text-rose-200/90"
    }
];

export const getThemeById = (id: number) => {
    return colorThemes[id % colorThemes.length];
}
